# fly.toml app configuration file generated for misty-water-9489 on 2023-08-03T13:32:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-water-9489"
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
